"""Google Calendar integration for the AI Record Label.

Creates a calendar event whenever a new audio export is detected by the
file watcher.  Uses the OAuth token generated by mcp-google-calendar
(stored at ~/.hermes/google/mcp-google-calendar-token.json) so no
separate auth flow is needed.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

# ── Paths ─────────────────────────────────────────────────────────────────────

_HERMES_GOOGLE = Path.home() / ".hermes" / "google"
_CREDENTIALS_PATH = Path(
    os.environ.get("CREDENTIALS_PATH", str(_HERMES_GOOGLE / "credentials.json"))
)
_TOKEN_PATH = _CREDENTIALS_PATH.parent / "mcp-google-calendar-token.json"

# Calendar to write events to ("primary" = the account's default calendar).
CALENDAR_ID = os.environ.get("HERMES_CALENDAR_ID", "primary")


# ── Auth ──────────────────────────────────────────────────────────────────────


def _build_service():
    """Return an authenticated Google Calendar service object, or None on error."""
    try:
        from google.oauth2.credentials import Credentials
        from google.auth.transport.requests import Request
        from googleapiclient.discovery import build
    except ImportError:
        logger.warning(
            "google-api-python-client not installed; install it with: "
            "uv pip install google-api-python-client google-auth"
        )
        return None

    if not _TOKEN_PATH.exists():
        logger.warning(
            "Google Calendar token not found at %s. "
            "Run setup_mcp.sh or start mcp-google-calendar once to authenticate.",
            _TOKEN_PATH,
        )
        return None

    if not _CREDENTIALS_PATH.exists():
        logger.warning("credentials.json not found at %s", _CREDENTIALS_PATH)
        return None

    try:
        with open(_CREDENTIALS_PATH) as f:
            creds_data = json.load(f)
        installed = creds_data.get("installed", creds_data.get("web", {}))
        client_id = installed["client_id"]
        client_secret = installed["client_secret"]

        with open(_TOKEN_PATH) as f:
            token_data = json.load(f)

        token_scopes = str(
            token_data.get("scope") or "https://www.googleapis.com/auth/calendar.events"
        ).split()

        creds = Credentials(
            token=token_data.get("access_token"),
            refresh_token=token_data.get("refresh_token"),
            token_uri="https://oauth2.googleapis.com/token",
            client_id=client_id,
            client_secret=client_secret,
            scopes=token_scopes,
        )

        # Refresh if expired.
        if creds.expired and creds.refresh_token:
            creds.refresh(Request())
            # Persist refreshed token so mcp-google-calendar can use it too.
            token_data.update({
                "access_token": creds.token,
                "expiry_date": int(creds.expiry.timestamp() * 1000) if creds.expiry else None,
            })
            with open(_TOKEN_PATH, "w") as f:
                json.dump(token_data, f, indent=2)

        return build("calendar", "v3", credentials=creds, cache_discovery=False)

    except Exception:
        logger.exception("Failed to build Google Calendar service")
        return None


# ── Public API ────────────────────────────────────────────────────────────────


def create_export_event(
    *,
    project_name: str,
    file_path: str | Path,
    bpm: float | None = None,
    version: int = 1,
    changed: bool = True,
    similarity: float | None = None,
    session_date: str | None = None,
    when: datetime | None = None,
) -> str | None:
    """Create a Google Calendar event marking an audio export.

    Returns the created event's HTML link, or None if creation failed.
    """
    service = _build_service()
    if service is None:
        return None

    now = when or datetime.now(tz=timezone.utc)
    # Calendar API wants RFC3339 strings with timezone.
    # Ensure the datetime is timezone-aware (UTC fallback).
    if now.tzinfo is None:
        now = now.replace(tzinfo=timezone.utc)
    start_iso = now.isoformat()
    # Events need a non-zero duration; use 15 minutes for an export marker.
    from datetime import timedelta
    end_iso = (now + timedelta(minutes=15)).isoformat()

    file_name = Path(file_path).name
    bpm_str = f"{bpm:.0f} BPM · " if bpm else ""
    change_str = f"Δ v{version}" if changed else f"v{version} (no change)"
    sim_str = f"  similarity {similarity:.0%}" if similarity is not None else ""

    summary = f"🎛 Export · {project_name} · {change_str}"
    description = (
        f"File: {file_name}\n"
        f"{bpm_str}{change_str}{sim_str}\n"
        f"Session date: {session_date or now.strftime('%Y-%m-%d')}\n"
        f"Full path: {file_path}"
    )

    event_body = {
        "summary": summary,
        "description": description,
        "start": {"dateTime": start_iso, "timeZone": "UTC"},
        "end": {"dateTime": end_iso, "timeZone": "UTC"},
        "colorId": "2",  # sage green
        "source": {
            "title": "AI Record Label",
            "url": "http://localhost:8086",
        },
    }

    try:
        created = (
            service.events()
            .insert(calendarId=CALENDAR_ID, body=event_body)
            .execute()
        )
        link = created.get("htmlLink", "")
        logger.info("Calendar event created: %s", link)
        return link
    except Exception:
        logger.exception("Failed to create Google Calendar event for %s", file_name)
        return None
